### ISSUE TITLE
publish can't create new packages (any more)

### ISSUE THREAD

**Issue by hseeberger** [softprops/bintray-sbt#46]
I don't have a lot of experience with Bintray, but 
- when I set up my first project last year, I could publish using bintray-sbt without any issues
- now, when I try to publish a new project, that fails until I create the package manually

The REST API docs state that in order to create a new package "licenses and vcs_url are mandatory for OSS package". Maybe the vcs_url has been added or made mandatory lately?

**Comment by softprops** [comment]
I'll have a look. I just published [0.2.0](http://notes.implicit.ly/post/112460523949/bintray-sbt-0-2-0) with some changes to their licenses requirements. I'll look into this `vcs_url` thing next

**Comment by hseeberger** [comment]
Thanks. I just verified that I still get "was not able to find or create a package for hseeberger in maven named test" for a non-existent package.

**Comment by softprops** [comment]
just published [0.2.1](http://notes.implicit.ly/post/114370226509/bintray-sbt-0-2-1) which should resolve the vcs url issue
